export const config = {
  port: parseInt(process.env.PORT || '3000', 10),
  mongoUri: process.env.MONGO_URI || 'mongodb://localhost:27018/melofy',
  redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
  openaiApiKey: process.env.OPENAI_API_KEY || '',
  openRouterApiKey: process.env.OPEN_ROUTER_API_KEY || '',
  geminiApiKey: process.env.GEMINI_API_KEY || '',
  translationModel: process.env.OPENAI_MODEL || 'google/gemini-3.7-flash',
  twoStepTranslation: process.env.TWO_STEP_TRANSLATION !== 'false',
  cacheTtlSeconds: parseInt(process.env.CACHE_TTL || '864000', 10),
  defaultSourceLanguage: 'auto',
  dailyTranslationLimit: parseInt(process.env.DAILY_TRANSLATION_LIMIT || '10', 10),
  rateLimitSalt: process.env.RATE_LIMIT_SALT || 'melofy-local-dev-salt',
  byokPrivateKey: process.env.BYOK_PRIVATE_KEY || '',
  posthogKey: process.env.POSTHOG_KEY || process.env.NEXT_PUBLIC_POSTHOG_KEY || '',
  posthogHost: process.env.POSTHOG_HOST || process.env.NEXT_PUBLIC_POSTHOG_HOST || 'https://us.i.posthog.com',
  langfusePublicKey: process.env.LANGFUSE_PUBLIC_KEY || '',
  langfuseSecretKey: process.env.LANGFUSE_SECRET_KEY || '',
  langfuseBaseUrl: process.env.LANGFUSE_BASE_URL || process.env.LANGFUSE_HOST || 'https://cloud.langfuse.com',
};
